# Generated by Django 5.2.1 on 2025-06-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jenis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=20)),
                ("deskripsi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Barang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kdbrg", models.CharField(max_length=8)),
                ("nama", models.CharField(max_length=75)),
                ("stok", models.IntegerField()),
                ("harga", models.BigIntegerField()),
                ("link_gambar", models.CharField(blank=True, max_length=150)),
                ("waktu_posting", models.DateTimeField(auto_now_add=True)),
                (
                    "jenis_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profil.jenis",
                    ),
                ),
            ],
        ),
    ]
