# Generated by Django 5.2.1 on 2025-06-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Projects',
        ),
    ]
