# Generated by Django 5.2.1 on 2025-06-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_rename_project_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='gallery',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
