# Generated by Django 5.2.1 on 2025-06-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_projects_gallery_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='gallery',
            field=models.ImageField(default='upload_file/g-lamp.jpg', upload_to='upload_file/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='upload_file/lamp.jpg', upload_to='upload_file/'),
            preserve_default=False,
        ),
    ]
