# Generated by Django 5.2.1 on 2025-07-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_alter_projects_gallery_alter_projects_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='isi',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='judul',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
        migrations.DeleteModel(
            name='Barang',
        ),
        migrations.DeleteModel(
            name='Jenis',
        ),
    ]
