# Generated by Django 5.2.1 on 2025-07-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_rename_isi_about_desc_rename_judul_about_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
