# Generated by Django 5.2.1 on 2025-07-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='css_icon',
            field=models.CharField(default='frontend', max_length=20),
            preserve_default=False,
        ),
    ]
