# Generated by Django 5.2.1 on 2025-07-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0009_service_css_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='upload_file/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('say', models.CharField(max_length=200)),
                ('author_img', models.ImageField(upload_to='upload_file/')),
                ('author', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
            ],
        ),
    ]
