# Generated by Django 5.2.1 on 2025-07-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0010_client_socialmedia_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='icon',
            field=models.FileField(upload_to='upload_file/'),
        ),
    ]
