# Generated by Django 5.2.1 on 2025-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0011_alter_client_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='say',
            field=models.TextField(),
        ),
    ]
