# Generated by Django 5.2.1 on 2025-08-21 17:44

from django.db import migrations
# import os
# from django.conf import settings
# from django.core.files import File

# def create_dummy_testimonials(apps, schema_editor):
#     Testimonial = apps.get_model("profil", "Testimonial")

#     if not Testimonial.objects.exists():
#       image_dir = os.path.join(settings.BASE_DIR, "static", "images", "avatars")
#       image_files = ["user-01.jpg", "user-02.jpg", "user-04.jpg"]
#       says = [
#         '"Flare brings a rare blend of strategic thinking and creative precision. They understand how to scale ideas without losing their soul—something we value deeply at Amazon."',
#         '"Flare’s ability to merge clarity with creativity is impressive. They help brands articulate their vision in a way that is both inspiring and grounded in real-world impact—something essential in today’s evolving landscape."',
#         '"Working with Flare felt like collaborating with an extension of our own team. Their insight into digital behavior and user-centric design aligns perfectly with the way we build at Google."'
#       ]
#       authors = ['Jeff Bezos', 'Satya Nadella', 'Sundar Pichai']
#       job_titles = ['CEO, Amazon', 'CEO, Microsoft', 'CEO, Google']

#       for idx, img_name in enumerate(image_files, start=1):
#         img_path = os.path.join(image_dir, img_name)
#         if os.path.exists(img_path):
#           with open(img_path, "rb") as f:
#             testimonial = Testimonial(
#               say=says[idx],
#               author=authors[idx],
#               job_title=job_titles[idx]
#             )
#             testimonial.photo.save(img_name, File(f), save=True)

class Migration(migrations.Migration):

  dependencies = [
    ('profil', '0012_alter_testimonial_say'),
  ]

  operations = [
    # migrations.RunPython(create_dummy_testimonials)
  ]
